### PR TITLE
Create es-ES.ini

### PR DESCRIPTION
**Pull request by COOLIGUAY**
Spanish locale.

Thank you for this incredible plugin!

There are 3 strings that are not available for translation:

Captura01
Captura02
Captura03

### CODE REVIEW

**Comment by FiniteSingularity** [comment]
Awesome!  Thank you for the PR, and for pointing out the three missing strings.  I'll give it a look in the next day or two, and merge in a change that includes those strings.

**Comment by FiniteSingularity** [comment]
@COOLIGUAY - If you're ok with this, I'd like to merge your Spanish Locale in, and then I'll push an update with those three labels available to the locale file. Could you then make a new PR with the additional three labels translated?

**Comment by COOLIGUAY** [comment]
Sure, no problem.
I will add all the new labels, also in future updates.

**Comment by FiniteSingularity** [comment]
@COOLIGUAY, I've just merged in a fix (as well as this PR).  When you have time, there are three new entries in the locale files: `CompositeBlurFilter.Background.None`, `CompositeBlurFilter.Box.Passes`, and `CompositeBlurFilter.EffectMask.Source.None`. When you have a few minutes, it would be great if you can add those translations to the new Spanish Locale file you've created.  Thanks again for your help on this!

**Comment by FiniteSingularity** [comment]
@all-contributors please add @COOLIGUAY for translation and bug

**Comment by COOLIGUAY** [comment]
Done! Glad to help

**Pull request merged**
